### ISSUE TITLE
Disable session_check_ip

### ISSUE THREAD

**Issue by jemisonf** [osulp/open-journals#3]
Based on (https://forum.pkp.sfu.ca/t/ojs-forgets-login/13512/2)[this] thread, the setting is currently causing some user sessions to be dropped.

**Comment by mellinma** [comment]
Ryan Ordway - would you please take a look at this issue?  @rordway

**Comment by mellinma** [comment]
@luisgreg99  would you have time to take a look at this issue - fischer couldn't fix it because he does't have the proper permissions.

**Comment by luisgreg99** [comment]
@jemisonf @mellinma  I've updated the setting to `session_check_ip = Off` on the server.

**Comment by jemisonf** [comment]
Thanks!
